blueprint:
  name: Anker SOLIX Netzladung bei Netzeinspeisung
  description: Aktiviert die Netzladung und setzt die Einspeisevorgabe auf die PV-Leistung, wenn f체r eine bestimmte Zeit eingespeist wird.
  domain: automation
  input:
    einspeisung_sensor:
      name: Sensor Netzeinspeisung
      selector:
        entity:
          domain: sensor
    pv_sensor:
      name: Sensor PV-Leistung
      selector:
        entity:
          domain: sensor
    soc_sensor:
      name: Sensor Batterieladestand (SoC)
      selector:
        entity:
          domain: sensor
    einspeisevorgabe_number:
      name: Entit채t Einspeisevorgabe (number)
      selector:
        entity:
          domain: number
    notladeoption_switch:
      name: Notladeoption Switch
      selector:
        entity:
          domain: switch
    hysterese_seconds:
      name: Hysterese (Sekunden)
      default: 30
      selector:
        number:
          min: 5
          max: 300
          unit_of_measurement: s
    soc_max:
      name: Maximaler SoC f체r Laden (%)
      default: 95
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

trigger:
  - platform: state
    entity_id: !input einspeisung_sensor
    for:
      seconds: !input hysterese_seconds

condition:
  - condition: numeric_state
    entity_id: !input einspeisung_sensor
    above: 0
  - condition: numeric_state
    entity_id: !input soc_sensor
    below: !input soc_max

action:
  # Notladeoption aktivieren
  - service: switch.turn_on
    target:
      entity_id: !input notladeoption_switch

  # Einspeisevorgabe setzen auf PV-Leistung
  - service: number.set_value
    target:
      entity_id: !input einspeisevorgabe_number
    data:
      value: >
        {{ states[inputs.pv_sensor] | float(0) | round(0) }}

  # R체cksetzung nach 2 Minuten
  - delay:
      seconds: 120
  - condition: numeric_state
    entity_id: !input einspeisung_sensor
    below: 1
  - service: switch.turn_off
    target:
      entity_id: !input notladeoption_switch
  - service: number.set_value
    target:
      entity_id: !input einspeisevorgabe_number
    data:
      value: 0

mode: restart
